site_name: Geospatial Information Network
site_author: Big Ten Academic Alliance Geospatial Information Network
# copyright : "&copy; 2016-2023"
noindex: true 

theme: 
      name: material
      highlightjs: true
      logo: images/btaa-logo-white.png
      font:
            text: helvetica neue
      custom_dir: overrides
      features:
            - navigation.top
            - navigation.indexes
            - navigation.instant
            - navigation.tabs
            - navigation.tabs.sticky
            - navigation.tracking
            - navigation.sections
            - navigation.path
            - navigation.prune
            - toc.follow

    
plugins:
      - tags:
            tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
                  kwds:
                        case: lower
            tags_file: library/index.md
                      
      - table-reader
      - search
      - open-in-new-tab
      - glightbox:
            touchNavigation: true
            loop: false
            effect: zoom
            slide_effect: slide
            width: 100%
            height: 100%
            zoomable: true
            draggable: true
            skip_classes:
                  - custom-skip-class-name
            auto_caption: true
            caption_position: top
      - blog:
            blog_dir: updates
            categories: false
            archive: false
            post_date_format: medium
            archive_date_format: yyyy
#       - optimize
#           enabled:!ENV [CI, false]
#       - pdf-export:
#             verbose: true
#             media_type: print

extra_css:
      - stylesheets/extra.css

extra_javascript:
      - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
      - javascripts/tablesort.js

markdown_extensions:
      - abbr
      - tables
      - attr_list
      - md_in_html
      - meta
      - footnotes
      - admonition
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - pymdownx.details
      - pymdownx.superfences:
            custom_fences:
                  - name: mermaid
                    class: mermaid
                    format: !!python/name:pymdownx.superfences.fence_code_format
                    showSequenceNumbers: true
      - pymdownx.snippets
      - pymdownx.magiclink
      - pymdownx.tasklist:
            custom_checkbox: true
      - pymdownx.emoji:
            emoji_index: !!python/name:materialx.emoji.twemoji
            emoji_generator: !!python/name:materialx.emoji.to_svg
            options:
                  custom_icons:
                        - overrides/.icons
      - pymdownx.tabbed:
            slugify: !!python/object/apply:pymdownx.slugs.slugify
                  kwds:
                        case: lower
      - toc:
              toc_depth: 3
              permalink: true
              permalink_title: Anchor link to this section for reference

extra:
      generator: false
      tags:
            library: libr
      social:
            - icon: material/email 
              link: https://geo.btaa.org/feedback
            - icon: simple/youtube
              link: https://www.youtube.com/@geobtaa1585

nav:

- Home: 'index.md'

- About:
      - 'about/index.md'
      - 'Participants': 'about/participants.md'
      - 'Committees': 'about/committees.md'
      - 'History': 'about/history.md'
      - 'Updates': 
            'updates/index.md'
      

- Technology:
      - 'technology/index.md'
      - 'BTAA Geoportal': 'technology/geoportal.md'
      - 'Admin Toolkit': 'technology/geomg.md'
      - 'Metadata Handbook': 'technology/metadataHandbook.md'

- User Resources:
      - Research Guides:
              - 'guides/index.md'
              - 'BTAA Geoportal Search strategies': 'guides/search-strategies.md'
              - 'Understanding metadata': 'guides/understanding-metadata.md'
              - 'Citing geospatial data':  'guides/cite-data.md'
              - 'Licensed data' : 'guides/licensed-data.md'
              - 'U.S. Census data' : 'guides/census.md'
              - 'Fire insurance maps'  : 'guides/fire-insurance.md'   
              - 'Public Land Survey System (PLSS) Plats' : 'guides/plss.md'

      - Tutorials:
              - 'tutorials/index.md'
              - '1. Types of Geospatial Information': 'tutorials/01_types-of-geospatial-information.md'
              - '2. Find Maps': 'tutorials/02_find-maps.md'
              - '3. Find Geospatial Data': 'tutorials/03_find-geospatial-data.md'
              - '4. Evaluate Geospatial Information': 'tutorials/04_evaluate-geospatial-information.md'
              - '5. Web Services': 'tutorials/05_web-services.md'
              - '6. Link Tabular Data': 'tutorials/06_link-tabular-data.md'
              - '7. Georeference': 'tutorials/07_georeference.md'
              - '8. Digitize': 'tutorials/08_digitize.md'
              - '9. Create Elevation Surface Models': 'tutorials/09_create-elevation-surface-models.md'
              - '10. Zonal Stats Tool': 'tutorials/10_zonal-stats-tool.md'
              - '11. Story Maps': 'tutorials/11_story-maps.md'
      

- Document Library:
      - 'library/index.md'
      - Scholarly Publications:
        - 'Journal Articles': 'library/articles.md'
#         - 'Presentations': 'library/presentations.md'
      - Reports & Guidelines:
              - 'Analytics Working Group Report': 'library/analytics-working-group-report.md'
              - 'Best Practices for ArcGIS Hubs': 'library/best-practices-open-data-portals.md'
              - 'Collection Development Policy': 'library/collection-development-policy.md'
              - 'Curation Priorities': 'library/curation-priorities.md'
              - 'Diverse Collections Report': 'library/diverse-collections.md'
              - 'Impact Report 2020': 'library/impactReport_2020-05.md'
              - 'Land acknowledgement Action Plan' : 'library/actionPlan.md' 
              - 'Licensed Data Implementation': 'library/licensed-data-implementation.md'
              - 'Original Content Guidelines': 'library/original-content.md'
              - 'Rates of Change for Open Data': 'library/rates-of-change.md'
              - 'Staff Time for Ephemeral Data': 'library/ephemeral-costs.md'
              - 'User Personas': 'library/user-personas.md'
      - Proposals & Charters:
              - 'Continuation Proposal 2021': 'library/continuation_2021.md'
              - 'A Spatial Data Infrastructure (SDI) for the BTAA': 'library/btaa-sdi-2019.md'
              - 'Continuation Proposal 2019': 'library/continuation_2019.md'
              - 'Continuation Proposal 2017': 'library/continuation_2017.md'
              - 'CIC Geospatial Data Discovery Project Charter (2015)': 'library/cic-charter.md'
              - 'Proposal for a Geospatial Data Discovery Project Across the CIC (2015)': 'library/cic-proposal.md'
   
- GIS Conference:
      - 'index' : 'conference/index.md'
      - 2023 Agenda: 'conference/2023.md'
      - Map Gallery Guidelines: 'conference/map-guidelines.md'
      - Past Conferences:
              - 2022: 'conference/2022.md'   
              - 2021: 'conference/2021.md'
              - 2020: 'conference/2020.md'
      

      




