site_name: Geospatial Information Network
site_author: Big Ten Academic Alliance Geospatial Information Network
copyright : "2023"
noindex: true 

theme: 
      name: material
      highlightjs: true
      logo: images/btaa-logo-white.png
      font:
            text: helvetica neue
#       palette:
#           primary: white
#           accent: black
      custom_dir: overrides
      features:
            - navigation.top
            - navigation.indexes
#             - navigation.instant
            - navigation.tabs
            - navigation.tabs.sticky
            - navigation.tracking
            - navigation.sections
#             - navigation.expand
            - navigation.path
            - navigation.prune
#             - toc.integrate
            - toc.follow

    
plugins:
      - table-reader
      - search
      - open-in-new-tab
      - glightbox:
            touchNavigation: true
            loop: false
            effect: zoom
            slide_effect: slide
            width: 100%
            height: 100%
            zoomable: true
            draggable: true
            skip_classes:
                  - custom-skip-class-name
            auto_caption: true
            caption_position: top
#      - blog:
#            categories: false
#            archive: false
#      - optimize:
#            enabled: !ENV [CI, false]
#       - pdf-export:
#             verbose: true
#             media_type: print

extra_css:
      - stylesheets/extra.css
  
extra_javascript:
      - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
      - javascripts/tablesort.js

markdown_extensions:
      - abbr
      - tables
      - attr_list
      - md_in_html
      - meta
      - admonition
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - pymdownx.details
      - pymdownx.superfences:
            custom_fences:
                  - name: mermaid
                    class: mermaid
                    format: !!python/name:pymdownx.superfences.fence_code_format
                    showSequenceNumbers: true
      - pymdownx.snippets
      - pymdownx.emoji:
            emoji_index: !!python/name:materialx.emoji.twemoji
            emoji_generator: !!python/name:materialx.emoji.to_svg
            options:
                  custom_icons:
                        - overrides/.icons
      - pymdownx.tabbed:
            alternate_style: true 
            slugify: !!python/object/apply:pymdownx.slugs.slugify
                  kwds:
                        case: lower
      - toc:
              toc_depth: 3
              permalink: true
              permalink_title: Anchor link to this section for reference


nav:

- Home: 'index.md'

- User Resources:
      - Tutorials:
            - 'tutorials/index.md'
            - '1. Types of Geospatial Information': 'tutorials/01_types-of-geospatial-information.md'
            - '2. Find Maps': 'tutorials/02_find-maps.md'
            - '3. Find Geospatial Data': 'tutorials/03_find-geospatial-data.md'
            - '4. Evaluate Geospatial Information': 'tutorials/04_evaluate-geospatial-information.md'
            - '5. Web Services': 'tutorials/05_web-services.md'
            - '6. Link Tabular Data': 'tutorials/06_link-tabular-data.md'
            - '7. Georeference': 'tutorials/07_georeference.md'
            - '8. Digitize': 'tutorials/08_digitize.md'
            - '9. Create Elevation Surface Models': 'tutorials/09_create-elevation-surface-models.md'
            - '10. Zonal Stats Tool': 'tutorials/10_zonal-stats-tool.md'
            - '11. Story Maps': 'tutorials/11_story-maps.md'

      - Search Guides:
            - 'Geoportal Search strategies': 'guides/search-strategies.md'
            - 'Understanding metadata': 'guides/understanding-metadata.md'
            - 'Licensed data' : 'guides/licensed-data.md'
            - 'Fire insurance maps'  : 'guides/fire-insurance.md'   
            - 'Public Land Survey System (PLSS) Plats' : 'guides/plss.md'
            - 'Census data' : 'guides/census.md'
            - 'Cite data':  'guides/cite-data.md'
                  
- Program Documentation:
      - BTAA Geoportal:
            - 'About the Geoportal' : 'geoportal.md'
            - 'Metadata Handbook': 'metadataHandbook.md'
      - Program Guidelines:
            - 'Land acknowledgement action plan' : 'actionPlan.md' 
            - 'Collection Development Policy': 'collection-development-policy.md'
            - 'Curation Priorities': 'curation-priorities.md'
      - Program Management:
            - 'Status Updates': 'blog/index.md'
            - 'Roadmap' : 'roadmap'
            - 'Impact Report 2020' : 'impactReport_2022-05.md'

- Publications:
      - 'Collections Blog': 'news.md'
      - 'Journal Articles': 'journal-articles.md'
      - 'Presentations': 'presentations.md'
      
- Conference:
      - 'index' : 'conference/index.md'
      - Past Conferences:
            - 2022: 'conference/2022/agenda.md'   
      - Map Gallery:
            - '2022' : 'conference/map-gallery/2022.md'
      

      
- About Us:
      - 'About the BTAA-GIN' : 'about-btaa-gin.md'
      - Committees:
            - 'Executive': 'committees/executive.md'
            - 'Steering': 'committees/steering.md'
            - 'Community Engagment & Education': 'committees/cee.md'
            - 'Metadata': 'committees/metadata.md'
            - 'Interface': 'committees/interface.md'
            - 'Collections Development': 'committees/cd.md'
      - 'Contact': 'contact.md'



