- title: Zeus
  content: Lorem ipsum dolor sit amet.
  image: ./docs/images/omg-logo.png
- title: Athena
  content: Lorem ipsum dolor sit amet.
  image: ./docs/images/omg-logo.png

- title: Poseidon
  content: Lorem ipsum dolor sit amet.
  image: ./docs/images/omg-logo.png

- title: Artemis
  content: Lorem ipsum dolor sit amet.
  image: ./docs/images/omg-logo.png

- title: Ares
  content: Lorem ipsum dolor sit amet.
  image: ./docs/images/omg-logo.png

- title: Nike
  content: Lorem ipsum dolor sit amet.
  image: ./docs/images/omg-logo.png


